oauthClient:
  redirectUris:
    - ${CLI_OKTA_REVERSE_DOMAIN}:/callback
  postLogoutRedirectUris:
    - ${CLI_OKTA_REVERSE_DOMAIN}:/logout
  applicationType: native

directions: |+2
  Okta configuration written to: okta.properties
  Run the app in Android Studio:
    • Create a target for the app by either configuring a Android virtual device (emulator) or connecting a physical device.
    • Run the app by clicking the Run button in the toolbar.
