oauthClient:
  redirectUris:
    - ${CLI_OKTA_REVERSE_DOMAIN}:/callback
  postLogoutRedirectUris:
    - ${CLI_OKTA_REVERSE_DOMAIN}:/logout
  applicationType: native

directions: |+2
  Okta configuration written to: okta.properties
  Run instructions for Android studio:
    • configure an Android virtual device (emulator) or connect a real device to Android Studio
    • run the application using 'Shift+F10' on Windows/Linux, 'Control+R' on macOS, or click 'Run' button in the toolbar.
